# Generated by Django 5.0.6 on 2024-05-11 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carreras',
            fields=[
                ('IDcarrera', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('duracion', models.IntegerField()),
                ('horario', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('DNI', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('edad', models.IntegerField()),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.carreras')),
            ],
        ),
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('IDmateria', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('duracion', models.CharField(max_length=50)),
                ('horario', models.CharField(max_length=20)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.carreras')),
            ],
        ),
    ]
