# Generated by Django 5.0.6 on 2024-05-12 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumnos',
            old_name='DNI',
            new_name='dni',
        ),
        migrations.RenameField(
            model_name='alumnos',
            old_name='carrera',
            new_name='id_carrera',
        ),
        migrations.RenameField(
            model_name='carreras',
            old_name='IDcarrera',
            new_name='id_carrera',
        ),
        migrations.RenameField(
            model_name='materias',
            old_name='carrera',
            new_name='id_carrera',
        ),
        migrations.RenameField(
            model_name='materias',
            old_name='IDmateria',
            new_name='id_materia',
        ),
        migrations.AddField(
            model_name='carreras',
            name='precio',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='edad',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='carreras',
            name='duracion',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='carreras',
            name='nombre',
            field=models.CharField(max_length=40),
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id_matricula', models.IntegerField(primary_key=True, serialize=False)),
                ('precio_matricula', models.CharField(max_length=11)),
                ('precio_seguro', models.CharField(max_length=10)),
                ('dni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumnos')),
            ],
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id_pagos', models.IntegerField(primary_key=True, serialize=False)),
                ('monto', models.CharField(max_length=10)),
                ('fecha', models.DateField()),
                ('observacion', models.CharField(max_length=50)),
                ('dni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumnos')),
                ('id_carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.carreras')),
            ],
        ),
    ]
