# Generated by Django 5.0.6 on 2024-05-12 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_rename_dni_alumnos_dni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carreras',
            name='id_carrera',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='materias',
            name='id_materia',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='id_matricula',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='id_pagos',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
