# Generated by Django 5.0.6 on 2024-05-12 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_alter_carreras_id_carrera_alter_materias_id_materia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carreras',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
