# Generated by Django 5.0.6 on 2024-05-16 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0008_meses'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='mes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='alumnos.meses'),
            preserve_default=False,
        ),
    ]
