# Generated by Django 5.0.6 on 2024-05-16 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0008_meses_pagos_mes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagos',
            name='mes',
        ),
        migrations.DeleteModel(
            name='Meses',
        ),
    ]
